name: JukeBoxPE
version: 0.1.0
api: [2.0.0]
author: "GlitchPlayer & Others"
description: "Jukebox from bukkit plugin"
main: JukeboxPE\Main

commands:
  music:
  permission: JukeboxPE.music
  description: "JukeboxPE's main command"
  usage: "/music <Next | Stop | Start>"

permissions:
  JukeboxPE.cmd:
    default: op
    children:
      JukeboxPE.cmd.music:
        default: op
  JukeboxPE.sound:
    default:true
